language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
 - chmod +x /phpunit.xml

script:
  - ./phpunit.xml

notifications:
  irc:
    channels:
      - "chat.freenode.net##add"
    on_success: change
    on_failure: always