language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

before_script:
 - composer install
 - chmod +x Tests/phpunit.xml.dist

script:
  - phpunit --configuration Tests/phpunit.xml.dist

notifications:
  irc:
    channels:
      - "chat.freenode.net##add"
    on_success: change
    on_failure: always